/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include<stdio.h>
#include<stdint.h>
#include<stdlib.h>

typedef volatile unsigned int vuint32_t;



#define GPIOA_BASE	0X40010800
#define GPIO_CRH 	*(volatile uint32_t*)(GPIOA_BASE+0x04)
#define GPIOA_ODR	*(volatile uint32_t*)(GPIOA_BASE+0x0C)
int main(void)
{
	GPIO_CRH &=0xFF0FFFFF;
	GPIO_CRH |=0x00200000;
	while(1)
	{
		GPIOA_ODR |=1<<13;
			for(int i=0;i<5000;i++);
			GPIOA_ODR &=~(1<<13);
			for(int i=0;i<5000;i++);
	}
}
